openapi: '3.0.2'
info:
  title: FlixPicks Database API
  version: '1.0.0'

servers:
  - url: '/api'

components:
  schemas:
    User:
      type: object
      required:
        - username
        - email
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        fname:
          type: string
        lname:
          type: string
        role:
          type: string
  parameters:
    username:
      name: "username"
      description: "username"
      in: path
      required: True
      schema:
        type: "string"

tags:
  - name: Users
    description: User profile information for FlixPicks
  - name: Interactions
    description: User interactions with media through FlixPicks

paths:
  /users:
    get:
      summary: Display all users
      tags:
        - Users
      operationId: userdata.users.show_all
      responses:
        '200':
          description: OK
    post:
      summary: Add new user
      tags:
        - Users
      operationId: "userdata.users.add"
      requestBody:
        description: "User to add"
        required: true
        content:
          application/json:
            schema:
                x-body-name: "user"
                $ref: "#/components/schemas/User"
      responses:
        "201":
          description: "New user added successfully"
        "422":
          description: "Username or E-mail provided already exists"    

  /users/{id}:
    get:
      summary: Find existing user by user id
      tags:
        - Users
      operationId: userdata.users.lookup_by_id
      responses:
        '200':
          description: OK
        '404':
          description: User not found
 
  /users/username/{username}:
    get:
      summary: Find existing user by username
      tags:
        - Users
      operationId: userdata.users.lookup_by_username
      responses:
        '200':
          description: OK
        '404':
          description: User not found

  /users/email/{email}:
    get:
      summary: Find existing user by E-mail address
      tags:
        - Users
      operationId: userdata.users.lookup_by_email
      responses:
        '200':
          description: OK
        '404':
          description: User not found

  /users/update/{username}/full:
    put:
      summary: Update User's Profile (All Items)
      tags:
        - Users
      operationId: userdata.users.update_full
      parameters:
        - $ref: "#/components/parameters/username"
      requestBody:
        description: "Updated user information"
        required: true
        content:
          application/json:
            schema:
                x-body-name: "user"
                $ref: "#/components/schemas/User"
      responses:
        "200":
          description: "User updated successfully"
        '404':
          description: User not found
  
  /users/update/{username}/password:
    patch:
      summary: Update User's Password
      tags:
        - Users
      operationId: userdata.users.update_password
      parameters:
        - $ref: "#/components/parameters/username"
      requestBody:
        description: "New user password to store"
        required: true
        content:
          application/json:
            schema:
                x-body-name: "data"
                type: object
                properties:
                  password:
                    type: string
      responses:
        "200":
          description: "User updated successfully"
        '404':
          description: User not found
  
  /users/update/{username}/role:
    patch:
      summary: Update User's Role
      tags:
        - Users
      operationId: userdata.users.update_role
      parameters:
        - $ref: "#/components/parameters/username"
      requestBody:
        description: "New user role to store"
        required: true
        content:
          application/json:
            schema:
                x-body-name: "data"
                type: object
                properties:
                  role:
                    type: string
      responses:
        "200":
          description: "User updated successfully"
        '404':
          description: User not found
  
  /users/update/{username}/last_login:
    patch:
      summary: Update User's Last Login
      tags:
        - Users
      operationId: userdata.users.update_last_login
      parameters:
        - $ref: "#/components/parameters/username"
      responses:
        "200":
          description: "User updated successfully"
        '404':
          description: User not found
  
  /users/update/{username}/limit_subscriptions:
    patch:
      summary: Update User's Setting for Limit to Subscriptions
      tags:
        - Users
      operationId: userdata.users.update_limit_subscriptions
      parameters:
        - $ref: "#/components/parameters/username"
      requestBody:
        description: "New user value to store"
        required: true
        content:
          application/json:
            schema:
                x-body-name: "data"
                type: object
                properties:
                  limit_subscriptions:
                    type: boolean
      responses:
        "200":
          description: "User updated successfully"
        '404':
          description: User not found
